spring:
  main:
    web-application-type: reactive
  application:
    name: GatewayService
  datasource:
    url: jdbc:mysql://localhost:3306
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  address: 0.0.0.0
  port: 8085
  error:
    include-exception: true
    include-message: always

logging:
  file:
    name: ./GatewayService.log

gateway:
  idm: http://localhost:8082
  movies: http://localhost:8083
  billing: http://localhost:8084
  authenticate-path: /authenticate
  max-logs: 10